Modified index.html and css files
edubew/microverse_hello pull request #1
Opened 2022-02-15 16:31 UTC by edubew

## In this milestone I was able to:
- Create a new branch intro-microverse
- Add README.md file to the microverse_hello
- Created index.html file and added a h1 tag to it
- Created css file and styled h1 tag
- Added linters and checked for linters errors

2022-02-15 19:00 UTC, mateo951 requested changes
### Hi @edubew,

Welcome to Microverse and congrats on making your first project 💪😎 

📝👌 **Your project highlights** 🔥😎
- Linters are setup correctly ✔ 
- Nice README file 🚀 Well done!
- Great use of GitHub Flow 🤯
- Nice PR 🤓 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._
- [ ]  Kindly add node_modules and test.md to the .gitignore file so we practice for the near future when we work with dependencies 🧐 Please also delete the test.md from your remote repository 🙌

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-17 21:15 UTC, prolajumokeoni requested changes
Hi @edubew,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
- Good readme ✔️ 
- Good PR ✔️ 
- No linter errors ✔️ 
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 21:15 UTC, prolajumokeoni commented on .gitignore
> +test.md
- [ ] Kindly make sure test.md is ignored by git, just as the previous reviewer requested, [The reason it isn't working is (probably) because you added some of those files before you added the .gitignore - so you have to remove them from git before they're able to be ignored.](https://stackoverflow.com/questions/18418718/git-still-adds-and-tracks-folders-marked-in-gitignore)
- I suggest you delete test.md file  locally, push to github and create another test.md file and push to github, you would see the file has been ignored 😉

2022-02-18 20:36 UTC, edubew commented on .gitignore
> +test.md
Hello @prolajumokeoni,
 I have made the changes as you requested, but I am not certain that I have done the right thing. Could you please confirm that for me?

2022-02-19 14:04 UTC, Donard97 approved these changes
## Hi @edubew , 👋  


_Well done on finishing the first project! 👏 💯_ 

**Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:** 

## Congratulations! 🎉 

![giphy (11)](https://user-images.githubusercontent.com/74506933/154804100-bdc285f0-e313-43eb-aa6a-b566a164d30b.gif)

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-19 14:09 UTC, merged